# Generated by Django 3.0.6 on 2020-05-11 07:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20200511_1310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_Comment',
            new_name='PostComment',
        ),
    ]
