# Generated by Django 3.0.6 on 2020-06-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200603_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
